# Generated by Django 5.0 on 2023-12-14 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_crs', '0004_remove_customer_current_debt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='api_crs.customer'),
        ),
    ]
